"""
ai_enrich_reviews.py — AI-Powered Review Enrichment
=====================================================
Reads raw customer reviews from the Bronze layer and enriches each record
with a sentiment label ('Positive' / 'Neutral' / 'Negative'), a complaint
category, and a satisfaction score (1–5).

Mode A (Rule-Based NLP): Default primary mode — always used when the API key
             is absent or invalid. The client is validated ONCE at startup
             so the pipeline never hangs on bad credentials.
Mode B (Gemini API): Optional enhanced mode, used when GEMINI_API_KEY is set
             and valid, enabling LLM-powered sentiment extraction.
"""
import os
import sys
import json
import re
import pandas as pd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Paths & DB Config
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
REVIEWS_FILE = os.path.join(DATA_DIR, "bronze", "customer_reviews.csv")

DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "db_dwh")
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASS = os.getenv("DB_PASS", "your_postgres_password")


def get_db_engine():
    db_url = f"postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    return create_engine(db_url)


# ---------------------------------------------------------------------------
# One-time API key validation
# The client is built ONCE here, not inside the per-review loop.
# If validation fails for any reason (missing key, SSL error, bad key),
# _GEMINI_CLIENT is set to None and Mode A (rule-based) is used for the
# entire run — avoiding 2,000 failed API calls.
# ---------------------------------------------------------------------------
def _build_gemini_client():
    """
    Attempts to build and validate a Gemini client using the GEMINI_API_KEY
    environment variable. Returns a valid client or None.
    """
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        print("  [Mode A] No GEMINI_API_KEY found — using rule-based NLP enrichment.")
        return None
    try:
        from google import genai
        client = genai.Client(api_key=api_key)
        # Cheap probe: list models to confirm the key is valid
        _ = client.models.list()
        print("  [Mode B] Gemini API key validated — using LLM enrichment.")
        return client
    except Exception as e:
        print(f"  [Mode A] Gemini API validation failed ({type(e).__name__}): {e}")
        print("  [Mode A] Falling back to rule-based NLP enrichment for this run.")
        return None


_GEMINI_CLIENT = _build_gemini_client()


# ---------------------------------------------------------------------------
# Rule-Based NLP Enrichment (Mode A)
# Expanded keyword sets to match the 21 review templates generated by
# generate_source_data.py. Returns (sentiment, complaint_category, score).
# ---------------------------------------------------------------------------
_NEGATIVE_WORDS  = ["delayed", "delay", "missed", "stuck", "disruption", "cancelled",
                     "lost", "damaged", "dented", "broken", "slow", "ignored",
                     "unhelpful", "substandard", "dirty", "chaotic", "misleading",
                     "unreliable", "disappointing", "too high", "extra fees"]
_POSITIVE_WORDS  = ["friendly", "helpful", "great", "excellent", "fantastic", "smooth",
                     "comfortable", "punctual", "on-time", "clean", "reliable", "solid",
                     "amazing", "exceptional", "above and beyond", "good", "decent"]
_DELAY_WORDS     = ["delay", "delayed", "late", "stuck at the gate", "departure delay",
                     "minutes", "departure", "connecting"]
_BAGGAGE_WORDS   = ["bag", "baggage", "luggage", "suitcase", "checked", "carousel",
                     "lost luggage", "lost bag"]
_SERVICE_WORDS   = ["service", "staff", "attendant", "crew", "cabin", "boarding",
                     "hospitality", "food", "meal", "inflight", "in-flight"]
_PRICING_WORDS   = ["price", "prices", "pricing", "ticket", "fare", "fares", "cost",
                     "expensive", "deal", "cheap", "free baggage", "extra fees", "allowance"]


def _rule_based_analyze(review_text: str) -> tuple[str, str, int]:
    """
    Classifies review text using an expanded keyword-matching heuristic.

    Returns:
        Tuple of (sentiment, complaint_category, satisfaction_score).
    """
    t = review_text.lower()

    # --- Detect complaint category (mutually exclusive, priority order) ---
    is_delay   = any(kw in t for kw in _DELAY_WORDS)
    is_baggage = any(kw in t for kw in _BAGGAGE_WORDS)
    is_service = any(kw in t for kw in _SERVICE_WORDS)
    is_pricing = any(kw in t for kw in _PRICING_WORDS)

    is_positive = any(kw in t for kw in _POSITIVE_WORDS)
    is_negative = any(kw in t for kw in _NEGATIVE_WORDS)

    # --- Assign category + sentiment + score ---
    if is_delay:
        if is_positive and not is_negative:
            return "Neutral", "Delay", 3
        return "Negative", "Delay", 1 if is_negative else 2

    if is_baggage:
        if is_positive and "intact" in t:
            return "Positive", "None", 5
        return "Negative", "Baggage", 1 if is_negative else 2

    if is_pricing:
        if any(kw in t for kw in ["deal", "fantastic", "great", "good value"]):
            return "Positive", "Pricing", 5
        if any(kw in t for kw in ["fair", "reasonable"]):
            return "Neutral", "Pricing", 3
        return "Negative", "Pricing", 2

    if is_service:
        if is_positive and not is_negative:
            return "Positive", "Service", 5
        if is_negative:
            return "Negative", "Service", 2
        return "Neutral", "Service", 3

    # --- Generic positive / negative / neutral fallback ---
    if is_positive and not is_negative:
        return "Positive", "None", 5
    if is_negative and not is_positive:
        return "Negative", "None", 2
    if is_positive and is_negative:
        return "Neutral", "None", 3

    return "Positive", "None", 4   # truly neutral / generic


# ---------------------------------------------------------------------------
# Per-Review Enrichment Dispatcher
# ---------------------------------------------------------------------------
def analyze_review_text(review_text: str) -> tuple[str, str, int]:
    """
    Routes each review to Mode A (rule-based NLP) or Mode B (Gemini LLM).

    The Gemini client is pre-built once at module load time. If the client
    is None (key absent or invalid), rule-based mode is used for ALL reviews
    without any further API attempts.

    Args:
        review_text: Raw customer review string.

    Returns:
        Tuple of (sentiment, complaint_category, satisfaction_score).
    """
    if _GEMINI_CLIENT is not None:
        try:
            prompt = (
                "Analyze the following flight review. Return ONLY a JSON object with keys:\n"
                "- \"sentiment\": \"Positive\", \"Neutral\", or \"Negative\"\n"
                "- \"complaint_category\": \"Delay\", \"Baggage\", \"Service\", \"Pricing\", or \"None\"\n"
                "- \"satisfaction_score\": integer 1 to 5\n\n"
                f"Review: \"{review_text}\""
            )
            response = _GEMINI_CLIENT.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
            )
            res_text = response.text.strip()
            # Strip markdown code fences if present
            res_text = re.sub(r"^```(?:json)?\s*", "", res_text)
            res_text = re.sub(r"\s*```$", "", res_text)
            data = json.loads(res_text)
            return data["sentiment"], data["complaint_category"], int(data["satisfaction_score"])
        except Exception as e:
            # Log once per failure type, don't spam
            print(f"  [Mode B → A fallback] {type(e).__name__}: {e}")

    return _rule_based_analyze(review_text)


# ---------------------------------------------------------------------------
# Main Enrichment Pipeline
# ---------------------------------------------------------------------------
def run_ai_enrichment() -> None:
    """
    Loads raw reviews → enriches each with sentiment/category/score →
    performs dimension key lookups → loads to Fact_Customer_Feedback.
    """
    print("\n--- Starting Review Enrichment ---")
    mode = "Mode B (Gemini LLM)" if _GEMINI_CLIENT else "Mode A (Rule-Based NLP)"
    print(f"  Enrichment mode: {mode}")

    if not os.path.exists(REVIEWS_FILE):
        print(f"ERROR: {REVIEWS_FILE} not found. Run generate_source_data.py first.")
        sys.exit(1)

    df_reviews = pd.read_csv(REVIEWS_FILE)
    print(f"  Loaded {len(df_reviews)} raw customer review records.")

    engine = get_db_engine()

    # Load dimension keys for surrogate key lookup
    with engine.connect() as conn:
        dim_date    = pd.read_sql("SELECT date_key, full_date FROM dim_date", conn)
        dim_airline = pd.read_sql("SELECT airline_key, carrier_code FROM dim_airline", conn)

    if dim_airline.empty:
        print("ERROR: dim_airline is empty. Run transform_and_load.py first.")
        sys.exit(1)

    print(f"  Enriching {len(df_reviews):,} reviews...")
    enriched_rows = []
    for _, row in df_reviews.iterrows():
        sentiment, category, score = analyze_review_text(row["raw_review_text"])
        enriched_rows.append({
            "review_date":        row["review_date"],
            "carrier_code":       row["carrier_code"],
            "sentiment":          sentiment,
            "complaint_category": category,
            "satisfaction_score": score,
            "review_text":        row["raw_review_text"],
        })

    df_enriched = pd.DataFrame(enriched_rows)

    # Date type normalization for merge
    df_enriched["review_date"] = pd.to_datetime(df_enriched["review_date"]).dt.date
    dim_date["full_date"]      = pd.to_datetime(dim_date["full_date"]).dt.date

    # Surrogate key lookups
    df_merged = pd.merge(df_enriched, dim_date,    left_on="review_date",  right_on="full_date",   how="inner")
    df_merged = pd.merge(df_merged,   dim_airline, left_on="carrier_code", right_on="carrier_code", how="inner")

    final_cols = ["date_key", "airline_key", "sentiment", "complaint_category", "satisfaction_score", "review_text"]
    df_final   = df_merged[final_cols]

    # Truncate + reload (idempotent re-runs)
    with engine.connect() as conn:
        conn.execute(text("TRUNCATE TABLE Fact_Customer_Feedback RESTART IDENTITY;"))
        conn.commit()

    df_final.to_sql("fact_customer_feedback", engine, if_exists="append", index=False)

    # Print summary statistics
    sentiment_counts = df_final["sentiment"].value_counts().to_dict()
    category_counts  = df_final["complaint_category"].value_counts().to_dict()
    avg_score        = df_final["satisfaction_score"].mean()
    print(f"SUCCESS: {len(df_final):,} records loaded into Fact_Customer_Feedback.")
    print(f"  Avg satisfaction score : {avg_score:.2f}/5.0")
    print(f"  Sentiment distribution : {sentiment_counts}")
    print(f"  Top complaint category : {max(category_counts, key=category_counts.get)}")


if __name__ == "__main__":
    run_ai_enrichment()
