import psycopg2
import random
import os
from faker import Faker
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Database Configuration (loaded from .env)
# ---------------------------------------------------------------------------
DB_HOST: str = os.getenv("DB_HOST", "localhost")
DB_PORT: str = os.getenv("DB_PORT", "5432")
DB_NAME: str = os.getenv("DB_NAME_OLTP", os.getenv("DB_NAME", "db_oltp"))
DB_USER: str = os.getenv("DB_USER", "postgres")
DB_PASS: str = os.getenv("DB_PASS", "your_postgres_password")

fake = Faker()

# ---------------------------------------------------------------------------
# Full route table — all 8 carriers with diverse origin/destination pairs.
# Airport IDs match airports.csv reference data generated by generate_source_data.py.
#
# Format: (carrier_code, origin_airport_id, dest_airport_id)
# Carriers: DL, AA, UA, WN, AS, B6, F9, NK
# ---------------------------------------------------------------------------
VALID_ROUTES = [
    # Delta Air Lines (DL) — hub: Atlanta (10397), Detroit (11433)
    ("DL", 10397, 13303),   # Atlanta → Nashville
    ("DL", 11433, 12478),   # Detroit → New York (JFK)
    ("DL", 14869, 11433),   # Salt Lake City → Detroit
    ("DL", 15016, 10397),   # St. Louis → Atlanta
    ("DL", 11193, 12892),   # Cincinnati → Los Angeles
    ("DL", 10397, 15016),   # Atlanta → St. Louis
    ("DL", 12266, 10397),   # Houston → Atlanta
    ("DL", 13930, 12478),   # Chicago → New York (JFK)
    ("DL", 10397, 12892),   # Atlanta → Los Angeles
    ("DL", 11433, 13930),   # Detroit → Chicago

    # American Airlines (AA) — hub: Dallas (11298), Chicago (13930)
    ("AA", 12892, 10397),   # Los Angeles → Atlanta
    ("AA", 11298, 12892),   # Dallas → Los Angeles
    ("AA", 13930, 11298),   # Chicago → Dallas
    ("AA", 12478, 11298),   # New York → Dallas
    ("AA", 11298, 13204),   # Dallas → Orlando
    ("AA", 13930, 12892),   # Chicago → Los Angeles
    ("AA", 11298, 12266),   # Dallas → Houston
    ("AA", 12892, 14107),   # Los Angeles → Phoenix
    ("AA", 13204, 10397),   # Orlando → Atlanta
    ("AA", 12478, 13930),   # New York → Chicago

    # United Airlines (UA) — hub: Chicago (13930), Houston (12266)
    ("UA", 10397, 12892),   # Atlanta → Los Angeles
    ("UA", 12266, 13930),   # Houston → Chicago
    ("UA", 13930, 14771),   # Chicago → San Francisco
    ("UA", 14771, 12266),   # San Francisco → Houston
    ("UA", 12478, 13930),   # New York → Chicago
    ("UA", 13930, 12478),   # Chicago → New York
    ("UA", 12266, 12892),   # Houston → Los Angeles
    ("UA", 14771, 13930),   # San Francisco → Chicago
    ("UA", 12892, 14771),   # Los Angeles → San Francisco
    ("UA", 10397, 13930),   # Atlanta → Chicago

    # Southwest Airlines (WN) — hub: Dallas (11298), Las Vegas
    ("WN", 13303, 12478),   # Nashville → New York
    ("WN", 11298, 13204),   # Dallas → Orlando
    ("WN", 13204, 11298),   # Orlando → Dallas
    ("WN", 12892, 14107),   # Los Angeles → Phoenix
    ("WN", 14107, 12892),   # Phoenix → Los Angeles
    ("WN", 12266, 13204),   # Houston → Orlando
    ("WN", 13204, 12892),   # Orlando → Los Angeles
    ("WN", 10397, 13204),   # Atlanta → Orlando
    ("WN", 11298, 12892),   # Dallas → Los Angeles
    ("WN", 12892, 11298),   # Los Angeles → Dallas

    # Alaska Airlines (AS) — hub: Seattle (using Portland 14057 as proxy)
    ("AS", 14771, 14057),   # San Francisco → Portland
    ("AS", 14057, 14771),   # Portland → San Francisco
    ("AS", 14057, 13930),   # Portland → Chicago
    ("AS", 14771, 12892),   # San Francisco → Los Angeles
    ("AS", 12892, 14771),   # Los Angeles → San Francisco
    ("AS", 14869, 14771),   # Salt Lake City → San Francisco
    ("AS", 14771, 14869),   # San Francisco → Salt Lake City
    ("AS", 14057, 12892),   # Portland → Los Angeles
    ("AS", 12892, 14057),   # Los Angeles → Portland
    ("AS", 14771, 13930),   # San Francisco → Chicago

    # JetBlue Airways (B6) — hub: New York (12478), Boston
    ("B6", 12478, 13204),   # New York → Orlando
    ("B6", 13204, 12478),   # Orlando → New York
    ("B6", 12478, 14771),   # New York → San Francisco
    ("B6", 12478, 12892),   # New York → Los Angeles
    ("B6", 12892, 12478),   # Los Angeles → New York
    ("B6", 13204, 14107),   # Orlando → Phoenix
    ("B6", 14107, 13204),   # Phoenix → Orlando
    ("B6", 12478, 14107),   # New York → Phoenix
    ("B6", 10397, 12478),   # Atlanta → New York
    ("B6", 12478, 10397),   # New York → Atlanta

    # Frontier Airlines (F9) — hub: Denver (using Salt Lake City 14869 as proxy)
    ("F9", 14869, 13204),   # Salt Lake City → Orlando
    ("F9", 13204, 14869),   # Orlando → Salt Lake City
    ("F9", 14869, 12892),   # Salt Lake City → Los Angeles
    ("F9", 12892, 14869),   # Los Angeles → Salt Lake City
    ("F9", 14869, 10397),   # Salt Lake City → Atlanta
    ("F9", 14107, 11298),   # Phoenix → Dallas
    ("F9", 11298, 14107),   # Dallas → Phoenix
    ("F9", 14869, 13930),   # Salt Lake City → Chicago
    ("F9", 10397, 14869),   # Atlanta → Salt Lake City
    ("F9", 13930, 14869),   # Chicago → Salt Lake City

    # Spirit Airlines (NK) — focus: budget leisure routes
    ("NK", 13204, 12892),   # Orlando → Los Angeles
    ("NK", 12892, 13204),   # Los Angeles → Orlando
    ("NK", 13204, 14107),   # Orlando → Phoenix
    ("NK", 14107, 13204),   # Phoenix → Orlando
    ("NK", 12478, 13204),   # New York → Orlando
    ("NK", 13204, 12478),   # Orlando → New York
    ("NK", 12892, 11298),   # Los Angeles → Dallas
    ("NK", 11298, 13204),   # Dallas → Orlando
    ("NK", 10397, 13204),   # Atlanta → Orlando
    ("NK", 13204, 10397),   # Orlando → Atlanta
]

# ---------------------------------------------------------------------------
# Carrier-specific revenue profile (avg base fare USD)
# Reflects real-world positioning: legacy vs. budget carriers
# ---------------------------------------------------------------------------
CARRIER_REVENUE_PROFILE: dict[str, tuple[float, float]] = {
    "DL": (250.0, 650.0),   # Delta — premium pricing
    "AA": (230.0, 620.0),   # American — premium
    "UA": (240.0, 640.0),   # United — premium
    "AS": (200.0, 500.0),   # Alaska — mid-tier
    "B6": (180.0, 450.0),   # JetBlue — mid-tier
    "WN": (120.0, 350.0),   # Southwest — budget-friendly
    "F9": (90.0, 280.0),    # Frontier — ultra-low-cost
    "NK": (80.0, 260.0),    # Spirit — ultra-low-cost
}


def generate_dummy_bookings(num_records: int) -> list[tuple]:
    """
    Generates synthetic booking records covering all 8 airline carriers
    with carrier-specific revenue profiles and randomized routes.

    Each record contains a booking date (2024-01-01 to 2025-11-01),
    a random user ID, a route drawn from VALID_ROUTES, passenger count,
    and revenue calculated from the carrier's pricing profile.

    Args:
        num_records: Number of booking records to generate.

    Returns:
        A list of tuples ready for bulk INSERT into the Bookings table.
    """
    records = []
    start_date = datetime(2024, 1, 1)
    end_date = datetime(2025, 11, 1)

    for _ in range(num_records):
        carrier, origin, dest = random.choice(VALID_ROUTES)
        passengers = random.randint(1, 5)

        lo, hi = CARRIER_REVENUE_PROFILE[carrier]
        base_fare = random.uniform(lo, hi)
        revenue = round(passengers * base_fare, 2)

        user_id = random.randint(1001, 50000)
        booking_date = fake.date_time_between(start_date=start_date, end_date=end_date)
        records.append((booking_date, user_id, carrier, origin, dest, passengers, revenue))

    return records


def insert_to_db(records: list[tuple]) -> None:
    """
    Bulk-inserts generated booking records into the OLTP Bookings table.

    Rolls back and prints an error if the INSERT fails for any reason.
    Closes the connection in a finally block to prevent connection leaks.

    Args:
        records: List of booking tuples returned by generate_dummy_bookings().
    """
    conn = None
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            dbname=DB_NAME,
            user=DB_USER,
            password=DB_PASS,
        )
        cur = conn.cursor()

        sql = """
        INSERT INTO Bookings
        (booking_date, user_id, flight_carrier_code, flight_origin_id, flight_dest_id, passengers, revenue)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        """
        cur.executemany(sql, records)
        conn.commit()
        print(f"SUCCESS: {len(records)} booking records inserted into the Bookings table.")
        print(f"  Carriers covered: {sorted(set(r[2] for r in records))}")

    except (Exception, psycopg2.DatabaseError) as error:
        print(f"ERROR: {error}")
        if conn:
            conn.rollback()
    finally:
        if conn:
            cur.close()
            conn.close()


if __name__ == "__main__":
    NUM_RECORDS_TO_GENERATE = 50_000   # 10× expansion for meaningful differentiation

    print(f"Generating {NUM_RECORDS_TO_GENERATE:,} synthetic booking records across 8 airlines...")
    dummy_data = generate_dummy_bookings(NUM_RECORDS_TO_GENERATE)

    print(f"Inserting records into db_oltp ({DB_HOST}:{DB_PORT}/{DB_NAME})...")
    insert_to_db(dummy_data)